###############################################################################################
#########                           --Database Settings--                             #########
###############################################################################################
# dbprefix is currently unused
dbhost: 127.0.0.1:3306
dbname: emi
dbuser: emi
dbpass: 'secret'
dbprefix: 'ev_'